// simulate.c – Test harness for CROP generated code

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>

// Override the weak sensor functions generated by the compiler.
// For each sensor, the compiler generates:
//   bool sensor_<name>_read(type* value)
// We'll replace them with our own that read from a global variable.

// Global mock values – you can update these from keyboard or random.
float mock_moisture = 50.0;
float mock_temp = 25.0;
bool mock_flow = false;
bool mock_button = false;

// Override functions – add one for every sensor you have.
// Example: sensor moisture pin A0 range 0.0..100.0
bool sensor_moisture_read(float* value) {
    *value = mock_moisture;
    return true;
}

// Example: sensor temp I2C(0x68) -> f32
bool sensor_temp_read(float* value) {
    *value = mock_temp;
    return true;
}

// Example: sensor flow_meter pin D3
bool sensor_flow_meter_read(bool* value) {
    *value = mock_flow;
    return true;
}

// Override output functions to print state changes.
void output_water_pump_set(bool state) {
    static bool last = false;
    if (state != last) {
        printf("[OUTPUT] water_pump -> %s\n", state ? "ON" : "OFF");
        last = state;
    }
}

void output_heater_set(bool state) {
    static bool last = false;
    if (state != last) {
        printf("[OUTPUT] heater -> %s\n", state ? "ON" : "OFF");
        last = state;
    }
}

void output_status_led_set(bool state) {
    static bool last = false;
    if (state != last) {
        printf("[OUTPUT] status_led -> %s\n", state ? "ON" : "OFF");
        last = state;
    }
}

// Override millis() to allow time advancement.
static unsigned long sim_millis = 0;
unsigned long millis() {
    return sim_millis;
}

// Function to advance simulation time.
void advance_time(unsigned long ms) {
    sim_millis += ms;
}

// A simple keyboard input reader (non-blocking) to change mock values.
// You can implement a more sophisticated UI as needed.

int main(int argc, char** argv) {
    printf("CROP Simulation Environment\n");
    printf("Type commands:\n");
    printf("  m <value>   set moisture (0-100)\n");
    printf("  t <value>   set temperature\n");
    printf("  f <0|1>     set flow trigger\n");
    printf("  b <0|1>     set button\n");
    printf("  s           step one loop iteration (advance 1ms)\n");
    printf("  q           quit\n\n");

    // Call the generated setup()
    setup();

    char cmd[10];
    float val;
    int ival;

    while (1) {
        // Run one iteration of loop()
        loop();

        // Advance time by a small amount to simulate real-time.
        advance_time(10); // 10ms per loop

        // Check for user input (non-blocking not needed – we just wait for input).
        printf("\n> ");
        if (scanf("%s", cmd) != 1) break;

        if (cmd[0] == 'm') {
            scanf("%f", &val);
            mock_moisture = val;
            printf("Moisture set to %.1f\n", mock_moisture);
        } else if (cmd[0] == 't') {
            scanf("%f", &val);
            mock_temp = val;
            printf("Temperature set to %.1f\n", mock_temp);
        } else if (cmd[0] == 'f') {
            scanf("%d", &ival);
            mock_flow = (ival != 0);
            printf("Flow set to %d\n", mock_flow);
        } else if (cmd[0] == 'b') {
            scanf("%d", &ival);
            mock_button = (ival != 0);
            printf("Button set to %d\n", mock_button);
        } else if (cmd[0] == 's') {
            // step: advance time and run loop again
            // already done above
        } else if (cmd[0] == 'q') {
            break;
        } else {
            printf("Unknown command\n");
        }
    }

    return 0;
}
