#include "codegen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>

static FILE* output = NULL;
static int indent_level = 0;
static CompilerOptions* compiler_opts = NULL;
static int every_counter = 0;              // for unique IDs
static char rule_names[128][256];          // store rule names for loop()
static int rule_count = 0;

void generate_main_loop();
void generate_statement(ASTNode* node);
void generate_expr(ASTNode* node);

int get_indent_level() { return indent_level; }

void indent(int level) {
    for (int i = 0; i < level * 2; i++) fprintf(output, " ");
}

const char* c_type_name(DataType type) {
    switch (type) {
        case TYPE_U8: return "uint8_t";
        case TYPE_U16: return "uint16_t";
        case TYPE_U32: return "uint32_t";
        case TYPE_U64: return "uint64_t";
        case TYPE_I8: return "int8_t";
        case TYPE_I16: return "int16_t";
        case TYPE_I32: return "int32_t";
        case TYPE_I64: return "int64_t";
        case TYPE_F32: return "float";
        case TYPE_F64: return "double";
        case TYPE_BOOL: return "bool";
        case TYPE_VOID: return "void";
        default: return "void";
    }
}

const char* to_upper_case(const char* name) {
    static char buffer[256];
    int i;
    for (i = 0; name[i] && i < 255; i++) buffer[i] = toupper(name[i]);
    buffer[i] = '\0';
    return buffer;
}

const char* sanitize_name(const char* name) {
    static char buffer[256];
    strncpy(buffer, name, sizeof(buffer)-1);
    buffer[sizeof(buffer)-1] = '\0';
    for (int i = 0; buffer[i]; i++) {
        if (!((buffer[i] >= 'a' && buffer[i] <= 'z') ||
              (buffer[i] >= 'A' && buffer[i] <= 'Z') ||
              (buffer[i] >= '0' && buffer[i] <= '9') ||
              buffer[i] == '_')) buffer[i] = '_';
    }
    return buffer;
}

bool generate_c_code(ASTNode* node, const char* output_file, CompilerOptions* opts) {
    output = fopen(output_file, "w");
    if (!output) { fprintf(stderr, "ERROR: Cannot open output file\n"); return false; }
    compiler_opts = opts;
    indent_level = 0;
    every_counter = 0;
    rule_count = 0;

    fprintf(output, "// Generated by CROP Compiler V2.1.2\n");
    fprintf(output, "#include <stdint.h>\n#include <stdbool.h>\n#include <stdlib.h>\n#include <string.h>\n#include <math.h>\n\n");

    fprintf(output, "#ifdef ARDUINO\n#include <Arduino.h>\n#else\n");
    fprintf(output, "#define D0 0\n#define D1 1\n#define D2 2\n#define D3 3\n#define D4 4\n#define D5 5\n#define D6 6\n#define D7 7\n#define D8 8\n#define D9 9\n#define D10 10\n#define D11 11\n#define D12 12\n#define D13 13\n#define A0 14\n#define A1 15\n#define A2 16\n#define A3 17\n#define A4 18\n#define A5 19\n");
    fprintf(output, "typedef uint16_t pin_t;\n");
    fprintf(output, "static unsigned long millis_counter = 0;\n");
    fprintf(output, "__attribute__((weak)) unsigned long millis() { return millis_counter; }\n");
    fprintf(output, "__attribute__((weak)) void delay(unsigned long ms) {}\n");
    fprintf(output, "#define OUTPUT 1\n#define INPUT 0\n#define INPUT_PULLUP 2\n#define LOW 0\n#define HIGH 1\n#define RISING 1\n#define FALLING 0\n#define CHANGE 2\n");
    fprintf(output, "__attribute__((weak)) void pinMode(pin_t pin, int mode) {}\n");
    fprintf(output, "__attribute__((weak)) void digitalWrite(pin_t pin, int val) {}\n");
    fprintf(output, "__attribute__((weak)) int digitalRead(pin_t pin) { return 0; }\n");
    fprintf(output, "__attribute__((weak)) int analogRead(pin_t pin) { return 512; }\n");
    fprintf(output, "__attribute__((weak)) void attachInterrupt(pin_t pin, void (*fn)(), int mode) {}\n");
    fprintf(output, "#endif\n\n");

    generate_program(node);
    generate_main_loop();
    fclose(output);
    return true;
}

void generate_program(ASTNode* node) {
    if (!node || node->type != NODE_PROGRAM) return;
    fprintf(output, "// Global declarations\n\n");
    ASTList* list = node->children;
    int has_init = 0;
    ASTList* temp = list;
    while (temp) { if (temp->node->type == NODE_INIT) has_init = 1; temp = temp->next; }

    while (list) {
        if (list->node->type != NODE_INIT) generate_declaration(list->node);
        list = list->next;
    }

    if (has_init) {
        temp = node->children;
        while (temp) {
            if (temp->node->type == NODE_INIT) generate_init(temp->node);
            temp = temp->next;
        }
    } else {
        fprintf(output, "static void init_crop() {}\n\n");
    }
}

void generate_declaration(ASTNode* node) {
    if (!node) return;
    switch (node->type) {
        case NODE_SENSOR: case NODE_SENSOR_BUS: generate_sensor(node); break;
        case NODE_OUTPUT: generate_output(node); break;
        case NODE_VAR: case NODE_ARRAY_VAR: generate_var(node); break;
        case NODE_LET: generate_let(node); break;
        case NODE_RULE:
            // Save rule name for later loop generation
            if (node->value.string) {
                snprintf(rule_names[rule_count++], 256, "%s", node->value.string);
            }
            generate_rule(node);
            break;
        case NODE_EVERY: generate_every(node); break;
        case NODE_FN: generate_fn(node); break;
        case NODE_MACHINE: generate_machine(node); break;
        case NODE_INVARIANT: generate_invariant(node); break;
        case NODE_EMIT: generate_emit(node); break;
        case NODE_EXTERN: generate_extern(node); break;
        case NODE_UNSAFE: generate_unsafe(node); break;
        default: break;
    }
}

// ... (all other functions remain the same as before, but I'll include the full file for completeness)

// ============================================================
// Sensor, Output, Var, Rule, If, Every, Fn, Machine, etc.
// ============================================================

void generate_sensor(ASTNode* node) {
    if (!node) return;
    const char* name = node->name;
    const char* pin = node->value.string ? node->value.string : "0";
    const char* safe = sanitize_name(name);
    const char* upper = to_upper_case(safe);
    int poll_ms = 100;
    bool has_range = false;
    float range_min = 0.0, range_max = 100.0;

    if (node->children) {
        ASTList* list = node->children;
        while (list) {
            if (list->node->type == NODE_POLL && list->node->left) {
                poll_ms = list->node->left->value.integer;
            }
            list = list->next;
        }
    }

    if (node->right && node->right->type == NODE_RANGE) {
        has_range = true;
        if (node->right->left && node->right->left->type == NODE_INTEGER) range_min = node->right->left->value.integer;
        else if (node->right->left && node->right->left->type == NODE_FLOAT) range_min = node->right->left->value.float_val;
        if (node->right->right && node->right->right->type == NODE_INTEGER) range_max = node->right->right->value.integer;
        else if (node->right->right && node->right->right->type == NODE_FLOAT) range_max = node->right->right->value.float_val;
    }

    bool is_analog = (pin[0] == 'A' || pin[0] == 'a');
    fprintf(output, "// Sensor %s on pin %s\n", name, pin);
    fprintf(output, "#define SENSOR_%s_PIN %s\n", upper, pin);
    fprintf(output, "#define SENSOR_%s_POLL %d\n", upper, poll_ms);
    fprintf(output, "static bool sensor_%s_valid = false;\n", safe);
    fprintf(output, "static %s sensor_%s_value = 0;\n",
            is_analog ? (has_range ? "float" : "uint16_t") : "bool", safe);
    fprintf(output, "static unsigned long sensor_%s_last_read = 0;\n", safe);
    fprintf(output, "void sensor_%s_update() {\n", safe);
    fprintf(output, "  if (millis() - sensor_%s_last_read >= %d) {\n", safe, poll_ms);
    fprintf(output, "    sensor_%s_last_read = millis();\n", safe);
    if (is_analog) {
        if (has_range) {
            fprintf(output, "    int raw = analogRead(%s);\n", pin);
            fprintf(output, "    sensor_%s_value = (float)raw / 1023.0 * (%.2f - %.2f) + %.2f;\n",
                    safe, range_max, range_min, range_min);
        } else {
            fprintf(output, "    sensor_%s_value = analogRead(%s);\n", safe, pin);
        }
        fprintf(output, "    sensor_%s_valid = true;\n", safe);
    } else {
        fprintf(output, "    sensor_%s_value = digitalRead(%s);\n", safe, pin);
        fprintf(output, "    sensor_%s_valid = true;\n", safe);
    }
    fprintf(output, "  }\n}\n\n");
    fprintf(output, "static bool sensor_%s_read(%s* value) {\n", safe,
            is_analog ? (has_range ? "float" : "uint16_t") : "bool");
    fprintf(output, "  sensor_%s_update();\n", safe);
    fprintf(output, "  if (!sensor_%s_valid) return false;\n", safe);
    fprintf(output, "  *value = sensor_%s_value;\n", safe);
    fprintf(output, "  sensor_%s_valid = false;\n", safe);
    fprintf(output, "  return true;\n}\n\n");
    fprintf(output, "static %s sensor_%s_read_opt() {\n",
            is_analog ? (has_range ? "float" : "uint16_t") : "bool", safe);
    fprintf(output, "  %s val = 0;\n", is_analog ? (has_range ? "float" : "uint16_t") : "bool");
    fprintf(output, "  if (sensor_%s_read(&val)) return val;\n", safe);
    if (is_analog && has_range) fprintf(output, "  return NAN;\n");
    else if (is_analog) fprintf(output, "  return 0xFFFF;\n");
    else fprintf(output, "  return false;\n");
    fprintf(output, "}\n\n");
}

void generate_output(ASTNode* node) {
    if (!node) return;
    const char* name = node->name;
    const char* pin = node->value.string ? node->value.string : "0";
    const char* safe = sanitize_name(name);
    const char* initial = "OFF";
    if (node->right && node->right->type == NODE_STATE_LITERAL) initial = node->right->value.string;
    fprintf(output, "// Output %s on pin %s\n", name, pin);
    fprintf(output, "#define OUTPUT_%s_PIN %s\n", to_upper_case(safe), pin);
    fprintf(output, "static bool output_%s_state = %s;\n", safe, strcmp(initial, "ON") == 0 ? "true" : "false");
    fprintf(output, "void output_%s_set(bool state) {\n  output_%s_state = state;\n  digitalWrite(%s, state ? HIGH : LOW);\n}\n\n", safe, safe, pin);
    fprintf(output, "bool output_%s_get() {\n  return digitalRead(%s);\n}\n\n", safe, pin);
}

void generate_var(ASTNode* node) {
    if (!node) return;
    const char* name = node->name;
    const char* type = c_type_name(node->data_type);
    fprintf(output, "static %s %s", type, name);
    if (node->right) { fprintf(output, " = "); generate_expr(node->right); }
    fprintf(output, ";\n\n");
}

void generate_let(ASTNode* node) { (void)node; }

void generate_rule(ASTNode* node) {
    if (!node) return;
    const char* name = node->value.string ? node->value.string : "anon";
    const char* safe = sanitize_name(name);
    fprintf(output, "void rule_%s() {\n", safe);
    indent_level++;
    if (node->children) {
        ASTList* list = node->children;
        while (list) { generate_statement(list->node); list = list->next; }
    }
    indent_level--;
    fprintf(output, "}\n\n");
}

void generate_statement(ASTNode* node) {
    if (!node) return;
    switch (node->type) {
        case NODE_ASSIGN: {
            indent(indent_level);
            if (node->left && node->left->type == NODE_IDENTIFIER) {
                Symbol* sym = lookup_symbol(node->left->name);
                if (sym && sym->sym_type == SYM_OUTPUT) {
                    fprintf(output, "output_%s_set(", sanitize_name(node->left->name));
                    generate_expr(node->right);
                    fprintf(output, ");\n");
                } else {
                    fprintf(output, "%s = ", node->left->name);
                    generate_expr(node->right);
                    fprintf(output, ";\n");
                }
            }
            break;
        }
        case NODE_IF: generate_if(node); break;
        case NODE_RETURN:
            indent(indent_level); fprintf(output, "return");
            if (node->left) { fprintf(output, " "); generate_expr(node->left); }
            fprintf(output, ";\n"); break;
        case NODE_LET:
            indent(indent_level); fprintf(output, "// let %s = ", node->name);
            if (node->right) generate_expr(node->right);
            fprintf(output, ";\n"); break;
        case NODE_UNSAFE: generate_unsafe(node); break;
        case NODE_IDENTIFIER: {
            Symbol* sym = lookup_symbol(node->name);
            if (sym && (sym->sym_type == SYM_FN || sym->sym_type == SYM_EXTERN)) {
                indent(indent_level); generate_expr(node); fprintf(output, ";\n");
            }
            break;
        }
        case NODE_BINOP: case NODE_UNOP: case NODE_FUNCTION_CALL:
            indent(indent_level); generate_expr(node); fprintf(output, ";\n"); break;
        default:
            indent(indent_level);
            if (node->left && node->right) { generate_expr(node); fprintf(output, ";\n"); }
            break;
    }
}

void generate_if(ASTNode* node) {
    if (!node) return;
    indent(indent_level);
    fprintf(output, "if (");
    if (node->left) generate_expr(node->left);
    fprintf(output, ") {\n");
    indent_level++;
    if (node->children) {
        ASTList* list = node->children;
        while (list) { generate_statement(list->node); list = list->next; }
    }
    indent_level--;
    indent(indent_level);
    fprintf(output, "}");
    if (node->right) {
        if (node->right->type == NODE_ELSE_IF) {
            fprintf(output, " else ");
            generate_if(node->right);
        } else if (node->right->type == NODE_ELSE) {
            fprintf(output, " else {\n");
            indent_level++;
            if (node->right->children) {
                ASTList* list = node->right->children;
                while (list) { generate_statement(list->node); list = list->next; }
            }
            indent_level--;
            indent(indent_level);
            fprintf(output, "}");
        }
    }
    fprintf(output, "\n");
}

void generate_every(ASTNode* node) {
    if (!node) return;
    int id = every_counter++;
    int interval = (node->left && node->left->type == NODE_INTEGER) ? node->left->value.integer : 1000;
    fprintf(output, "static unsigned long every_%d_last = 0;\n", id);
    fprintf(output, "void every_%d() {\n", id);
    indent_level++;
    fprintf(output, "if (millis() - every_%d_last >= %d) {\n", id, interval);
    indent_level++;
    fprintf(output, "every_%d_last = millis();\n", id);
    if (node->children) {
        ASTList* list = node->children;
        while (list) { generate_statement(list->node); list = list->next; }
    }
    indent_level--;
    fprintf(output, "}\n");
    indent_level--;
    fprintf(output, "}\n\n");
}

void generate_fn(ASTNode* node) {
    if (!node) return;
    const char* name = node->name;
    const char* ret = c_type_name(node->data_type);
    fprintf(output, "%s %s(", ret, name);
    if (node->right && node->right->children) {
        ASTList* params = node->right->children;
        bool first = true;
        while (params) {
            if (params->node->type == NODE_PARAM) {
                if (!first) fprintf(output, ", ");
                fprintf(output, "%s %s", c_type_name(params->node->data_type), params->node->name);
                first = false;
            }
            params = params->next;
        }
    }
    fprintf(output, ") {\n");
    indent_level++;
    if (node->children) {
        ASTList* list = node->children;
        while (list) { generate_statement(list->node); list = list->next; }
    }
    if (node->data_type != TYPE_VOID) { indent(indent_level); fprintf(output, "return 0;\n"); }
    indent_level--;
    fprintf(output, "}\n\n");
}

void generate_machine(ASTNode* node) {
    if (!node) return;
    const char* name = node->name;
    const char* safe = sanitize_name(name);
    fprintf(output, "// Machine %s (stub)\n", name);
    fprintf(output, "static int machine_%s_state = 0;\n", safe);
    fprintf(output, "void machine_%s_process() {}\n\n", safe);
}

void generate_expr(ASTNode* node) {
    if (!node) return;
    switch (node->type) {
        case NODE_INTEGER: fprintf(output, "%d", node->value.integer); break;
        case NODE_FLOAT: fprintf(output, "%f", node->value.float_val); break;
        case NODE_BOOLEAN: fprintf(output, node->value.integer ? "true" : "false"); break;
        case NODE_IDENTIFIER: {
            Symbol* sym = lookup_symbol(node->name);
            if (sym && sym->sym_type == SYM_OUTPUT)
                fprintf(output, "output_%s_get()", sanitize_name(node->name));
            else
                fprintf(output, "%s", node->name);
            break;
        }
        case NODE_BINOP:
            fprintf(output, "("); generate_expr(node->left);
            fprintf(output, " %s ", node->value.string);
            generate_expr(node->right); fprintf(output, ")"); break;
        case NODE_UNOP:
            if (strcmp(node->value.string, "not") == 0) { fprintf(output, "!"); generate_expr(node->left); }
            else { fprintf(output, "%s", node->value.string); generate_expr(node->left); }
            break;
        case NODE_FUNCTION_CALL:
            fprintf(output, "%s(", node->name);
            if (node->children) {
                ASTList* args = node->children; bool first = true;
                while (args) { if (!first) fprintf(output, ", "); generate_expr(args->node); first = false; args = args->next; }
            }
            fprintf(output, ")"); break;
        case NODE_QUESTION:
            fprintf(output, "sensor_%s_read_opt()", sanitize_name(node->name)); break;
        case NODE_IS:
            generate_expr(node->left);
            fprintf(output, " == %s", strcmp(node->value.string, "ON") == 0 ? "true" : "false");
            break;
        case NODE_STATE_LITERAL:
            fprintf(output, "%s", strcmp(node->value.string, "ON") == 0 ? "true" : "false");
            break;
        default: fprintf(output, "/* unknown */"); break;
    }
}

void generate_invariant(ASTNode* node) {
    if (!node) return;
    const char* name = node->value.string ? node->value.string : "anon";
    fprintf(output, "static bool invariant_%s() { return (", sanitize_name(name));
    if (node->left) generate_expr(node->left);
    fprintf(output, "); }\n\n");
}

void generate_emit(ASTNode* node) {
    if (!node) return;
    fprintf(output, "static void emit_%s() { /* TODO */ }\n\n", sanitize_name(node->name));
}

void generate_init(ASTNode* node) {
    if (!node) return;
    fprintf(output, "static void init_crop() {\n");
    indent_level++;
    if (node->children) {
        ASTList* list = node->children;
        while (list) {
            if (list->node->type == NODE_UNSAFE) generate_unsafe(list->node);
            else { indent(indent_level); fprintf(output, "/* unknown init */\n"); }
            list = list->next;
        }
    }
    indent_level--;
    fprintf(output, "}\n\n");
}

void generate_unsafe(ASTNode* node) {
    if (!node) return;
    indent(indent_level);
    if (node->value.string) fprintf(output, "%s\n", node->value.string);
    else fprintf(output, "/* unsafe block */\n");
}

void generate_extern(ASTNode* node) {
    if (!node) return;
    fprintf(output, "extern %s %s(", c_type_name(node->data_type), node->name);
    if (node->children) {
        ASTList* params = node->children; bool first = true;
        while (params) {
            if (params->node->type == NODE_PARAM) {
                if (!first) fprintf(output, ", ");
                fprintf(output, "%s %s", c_type_name(params->node->data_type), params->node->name);
                first = false;
            }
            params = params->next;
        }
    }
    fprintf(output, ");\n\n");
}

// ============================================================
// MAIN LOOP GENERATION – NOW GENERATES CALLS
// ============================================================

void generate_main_loop() {
    fprintf(output, "__attribute__((weak)) void setup() { init_crop(); }\n\n");
    fprintf(output, "__attribute__((weak)) void loop() {\n");
    indent_level++;
    // Call every blocks (if any)
    if (every_counter > 0) {
        fprintf(output, "  // Periodic tasks\n");
        for (int i = 0; i < every_counter; i++) {
            fprintf(output, "  every_%d();\n", i);
        }
        fprintf(output, "\n");
    }
    // Call rules
    if (rule_count > 0) {
        fprintf(output, "  // Rules\n");
        for (int i = 0; i < rule_count; i++) {
            // rule_names[i] is the name string from the AST, but function name is sanitized
            char safe[256];
            strncpy(safe, rule_names[i], sizeof(safe)-1);
            for (int j = 0; safe[j]; j++) {
                if (!((safe[j] >= 'a' && safe[j] <= 'z') ||
                      (safe[j] >= 'A' && safe[j] <= 'Z') ||
                      (safe[j] >= '0' && safe[j] <= '9') ||
                      safe[j] == '_')) safe[j] = '_';
            }
            safe[255] = '\0';
            fprintf(output, "  rule_%s();\n", safe);
        }
        fprintf(output, "\n");
    }
    // Call state machines (simplified – we'll just call any machine_process functions)
    // Not implemented yet.
    indent_level--;
    fprintf(output, "}\n\n");

    // main() as before (weak)
    fprintf(output, "#ifndef ARDUINO\n");
    fprintf(output, "__attribute__((weak)) int main() { setup(); while(1) { loop(); millis_counter++; } return 0; }\n");
    fprintf(output, "#endif\n");
}

bool check_invariants(ASTNode* node) {
    (void)node;
    printf("  ✓ Invariants check passed (SMT verification not yet integrated)\n");
    return true;
}
