// ============================================================
// codegen.c - Code Generation Implementation
// ============================================================

#include "codegen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

// ============================================================
// Global state
// ============================================================

static FILE* output = NULL;
static int indent_level = 0;
static CompilerOptions* compiler_opts = NULL;
static int unique_counter = 0;

// ============================================================
// Helper functions
// ============================================================

int get_indent_level() {
    return indent_level;
}

void indent(int level) {
    for (int i = 0; i < level * 2; i++) {
        fprintf(output, " ");
    }
}

const char* c_type_name(DataType type) {
    switch (type) {
        case TYPE_U8: return "uint8_t";
        case TYPE_U16: return "uint16_t";
        case TYPE_U32: return "uint32_t";
        case TYPE_U64: return "uint64_t";
        case TYPE_I8: return "int8_t";
        case TYPE_I16: return "int16_t";
        case TYPE_I32: return "int32_t";
        case TYPE_I64: return "int64_t";
        case TYPE_F32: return "float";
        case TYPE_F64: return "double";
        case TYPE_BOOL: return "bool";
        case TYPE_VOID: return "void";
        default: return "void";
    }
}

const char* sanitize_name(const char* name) {
    // Replace spaces and special characters
    static char buffer[256];
    strncpy(buffer, name, sizeof(buffer) - 1);
    buffer[sizeof(buffer) - 1] = '\0';
    for (int i = 0; buffer[i]; i++) {
        if (!((buffer[i] >= 'a' && buffer[i] <= 'z') ||
              (buffer[i] >= 'A' && buffer[i] <= 'Z') ||
              (buffer[i] >= '0' && buffer[i] <= '9') ||
              buffer[i] == '_')) {
            buffer[i] = '_';
        }
    }
    return buffer;
}

// ============================================================
// Main code generation entry point
// ============================================================

bool generate_c_code(ASTNode* node, const char* output_file, CompilerOptions* opts) {
    output = fopen(output_file, "w");
    if (!output) {
        fprintf(stderr, "ERROR: Cannot open output file: %s\n", output_file);
        return false;
    }
    
    compiler_opts = opts;
    indent_level = 0;
    
    // Generate header
    fprintf(output, "// ============================================================\n");
    fprintf(output, "// Generated by CROP Compiler V2.1.2\n");
    fprintf(output, "// Source: %s\n", compiler_opts ? compiler_opts->input_file : "unknown");
    fprintf(output, "// Target: %s\n", compiler_opts ? compiler_opts->target : "native");
    fprintf(output, "// Date: %s", ctime(&(time_t){time(NULL)}));
    fprintf(output, "// ============================================================\n\n");
    
    // Include headers
    fprintf(output, "#include <stdint.h>\n");
    fprintf(output, "#include <stdbool.h>\n");
    fprintf(output, "#include <stdlib.h>\n");
    fprintf(output, "#include <string.h>\n");
    fprintf(output, "#include <math.h>\n\n");
    
    // Arduino/embedded compatibility
    fprintf(output, "// ============================================================\n");
    fprintf(output, "// Platform compatibility layer\n");
    fprintf(output, "// ============================================================\n\n");
    fprintf(output, "#ifdef ARDUINO\n");
    fprintf(output, "#include <Arduino.h>\n");
    fprintf(output, "#else\n");
    fprintf(output, "// Simulated environment\n");
    fprintf(output, "typedef uint16_t pin_t;\n");
    fprintf(output, "static unsigned long millis_counter = 0;\n");
    fprintf(output, "unsigned long millis() { return millis_counter; }\n");
    fprintf(output, "void delay(unsigned long ms) { /* simulated */ }\n");
    fprintf(output, "#define OUTPUT 1\n");
    fprintf(output, "#define INPUT 0\n");
    fprintf(output, "#define INPUT_PULLUP 2\n");
    fprintf(output, "#define LOW 0\n");
    fprintf(output, "#define HIGH 1\n");
    fprintf(output, "#define RISING 1\n");
    fprintf(output, "#define FALLING 0\n");
    fprintf(output, "#define CHANGE 2\n");
    fprintf(output, "void pinMode(pin_t pin, int mode) {}\n");
    fprintf(output, "void digitalWrite(pin_t pin, int val) {}\n");
    fprintf(output, "int digitalRead(pin_t pin) { return 0; }\n");
    fprintf(output, "int analogRead(pin_t pin) { return 512; }\n");
    fprintf(output, "void attachInterrupt(pin_t pin, void (*fn)(), int mode) {}\n");
    fprintf(output, "#endif\n\n");
    
    // Generate code
    generate_program(node);
    
    // Generate main loop
    generate_main_loop();
    
    fclose(output);
    return true;
}

// ============================================================
// Code generation functions
// ============================================================

void generate_program(ASTNode* node) {
    if (!node || node->type != NODE_PROGRAM) return;
    
    fprintf(output, "// ============================================================\n");
    fprintf(output, "// Global declarations\n");
    fprintf(output, "// ============================================================\n\n");
    
    // Generate all top-level declarations
    ASTList* list = node->children;
    while (list) {
        generate_declaration(list->node);
        list = list->next;
    }
}

void generate_declaration(ASTNode* node) {
    if (!node) return;
    
    switch (node->type) {
        case NODE_SENSOR:
        case NODE_SENSOR_BUS:
            generate_sensor(node);
            break;
        case NODE_OUTPUT:
            generate_output(node);
            break;
        case NODE_VAR:
        case NODE_ARRAY_VAR:
            generate_var(node);
            break;
        case NODE_LET:
            generate_let(node);
            break;
        case NODE_RULE:
            generate_rule(node);
            break;
        case NODE_EVERY:
            generate_every(node);
            break;
        case NODE_FN:
            generate_fn(node);
            break;
        case NODE_MACHINE:
            generate_machine(node);
            break;
        case NODE_INVARIANT:
            generate_invariant(node);
            break;
        case NODE_EMIT:
            generate_emit(node);
            break;
        case NODE_INIT:
            generate_init(node);
            break;
        case NODE_EXTERN:
            generate_extern(node);
            break;
        case NODE_UNSAFE:
            generate_unsafe(node);
            break;
        default:
            break;
    }
}

// ============================================================
// Hardware code generation
// ============================================================

void generate_sensor(ASTNode* node) {
    if (!node) return;
    
    const char* name = node->name;
    const char* pin = node->left ? node->left->name : "0";
    int poll_ms = 100;
    bool has_range = false;
    float range_min = 0.0, range_max = 100.0;
    
    // Get poll interval from children
    if (node->children) {
        ASTList* list = node->children;
        while (list) {
            if (list->node->type == NODE_POLL && list->node->left) {
                poll_ms = list->node->left->value.integer;
            }
            list = list->next;
        }
    }
    
    // Get range if present
    if (node->right && node->right->type == NODE_RANGE) {
        has_range = true;
        if (node->right->left && node->right->left->type == NODE_INTEGER) {
            range_min = node->right->left->value.integer;
        } else if (node->right->left && node->right->left->type == NODE_FLOAT) {
            range_min = node->right->left->value.float_val;
        }
        if (node->right->right && node->right->right->type == NODE_INTEGER) {
            range_max = node->right->right->value.integer;
        } else if (node->right->right && node->right->right->type == NODE_FLOAT) {
            range_max = node->right->right->value.float_val;
        }
    }
    
    bool is_analog = (pin[0] == 'A' || pin[0] == 'a');
    
    fprintf(output, "// Sensor: %s on pin %s\n", name, pin);
    fprintf(output, "#define SENSOR_%s_PIN %s\n", sanitize_name(name).toUpperCase(), pin);
    fprintf(output, "#define SENSOR_%s_POLL %d\n", sanitize_name(name).toUpperCase(), poll_ms);
    
    // Generate read function
    fprintf(output, "static bool sensor_%s_valid = false;\n", sanitize_name(name));
    fprintf(output, "static %s sensor_%s_value = 0;\n", 
            is_analog ? (has_range ? "float" : "uint16_t") : "bool",
            sanitize_name(name));
    fprintf(output, "static unsigned long sensor_%s_last_read = 0;\n", sanitize_name(name));
    fprintf(output, "\n");
    
    // Read function
    fprintf(output, "void sensor_%s_update() {\n", sanitize_name(name));
    fprintf(output, "  if (millis() - sensor_%s_last_read >= %d) {\n", sanitize_name(name), poll_ms);
    fprintf(output, "    sensor_%s_last_read = millis();\n", sanitize_name(name));
    
    if (is_analog) {
        if (has_range) {
            fprintf(output, "    int raw = analogRead(%s);\n", pin);
            fprintf(output, "    sensor_%s_value = (float)raw / 1023.0 * (%.2f - %.2f) + %.2f;\n",
                    sanitize_name(name), range_max, range_min, range_min);
            fprintf(output, "    sensor_%s_valid = true;\n", sanitize_name(name));
        } else {
            fprintf(output, "    sensor_%s_value = analogRead(%s);\n", sanitize_name(name), pin);
            fprintf(output, "    sensor_%s_valid = true;\n", sanitize_name(name));
        }
    } else {
        fprintf(output, "    sensor_%s_value = digitalRead(%s);\n", sanitize_name(name), pin);
        fprintf(output, "    sensor_%s_valid = true;\n", sanitize_name(name));
    }
    fprintf(output, "  }\n");
    fprintf(output, "}\n\n");
    
    // Read function with Option<T> semantics
    fprintf(output, "static bool sensor_%s_read(%s* value) {\n", sanitize_name(name),
            is_analog ? (has_range ? "float" : "uint16_t") : "bool");
    fprintf(output, "  sensor_%s_update();\n", sanitize_name(name));
    fprintf(output, "  if (!sensor_%s_valid) return false;\n", sanitize_name(name));
    fprintf(output, "  *value = sensor_%s_value;\n", sanitize_name(name));
    fprintf(output, "  sensor_%s_valid = false;\n", sanitize_name(name));
    fprintf(output, "  return true;\n");
    fprintf(output, "}\n\n");
    
    // Convenience function for ? operator
    fprintf(output, "static %s sensor_%s_read_opt() {\n", 
            is_analog ? (has_range ? "float" : "uint16_t") : "bool");
    fprintf(output, "  %s val = 0;\n", is_analog ? (has_range ? "float" : "uint16_t") : "bool");
    fprintf(output, "  if (sensor_%s_read(&val)) return val;\n", sanitize_name(name));
    fprintf(output, "  // Return NaN to indicate error (will be caught by ?)\n");
    if (is_analog && has_range) {
        fprintf(output, "  return NAN;\n");
    } else if (is_analog) {
        fprintf(output, "  return 0xFFFF;\n");
    } else {
        fprintf(output, "  return false;\n");
    }
    fprintf(output, "}\n\n");
}

void generate_output(ASTNode* node) {
    if (!node) return;
    
    const char* name = node->name;
    const char* pin = node->left ? node->left->name : "0";
    const char* initial = "OFF";
    
    if (node->right && node->right->type == NODE_STATE_LITERAL) {
        initial = node->right->value.string;
    }
    
    fprintf(output, "// Output: %s on pin %s\n", name, pin);
    fprintf(output, "#define OUTPUT_%s_PIN %s\n", sanitize_name(name), pin);
    fprintf(output, "static bool output_%s_state = %s;\n", sanitize_name(name), 
            strcmp(initial, "ON") == 0 ? "true" : "false");
    fprintf(output, "\n");
    
    fprintf(output, "void output_%s_set(bool state) {\n", sanitize_name(name));
    fprintf(output, "  output_%s_state = state;\n", sanitize_name(name));
    fprintf(output, "  digitalWrite(%s, state ? HIGH : LOW);\n", pin);
    fprintf(output, "}\n\n");
    
    fprintf(output, "bool output_%s_get() {\n", sanitize_name(name));
    fprintf(output, "  return digitalRead(%s);\n", pin);
    fprintf(output, "}\n\n");
}

// ============================================================
// Variable code generation
// ============================================================

void generate_var(ASTNode* node) {
    if (!node) return;
    
    const char* name = node->name;
    const char* type_name = c_type_name(node->data_type);
    
    fprintf(output, "// Variable: %s\n", name);
    
    if (node->type == NODE_ARRAY_VAR) {
        fprintf(output, "static %s %s[%d]", type_name, name, node->array_size);
        if (node->right) {
            fprintf(output, " = { ");
            // Generate initializer
            fprintf(output, "0");
            for (int i = 1; i < node->array_size; i++) {
                fprintf(output, ", 0");
            }
            fprintf(output, " }");
        }
        fprintf(output, ";\n\n");
    } else {
        fprintf(output, "static %s %s", type_name, name);
        if (node->right) {
            fprintf(output, " = ");
            generate_expr(node->right);
        }
        fprintf(output, ";\n\n");
    }
}

void generate_let(ASTNode* node) {
    // let is local, generated inline when used
    // No global declaration needed
}

// ============================================================
// Control flow code generation
// ============================================================

void generate_rule(ASTNode* node) {
    if (!node) return;
    
    const char* name = node->value.string ? node->value.string : "anonymous";
    const char* safe_name = sanitize_name(name);
    
    fprintf(output, "// Rule: %s\n", name);
    fprintf(output, "void rule_%s() {\n", safe_name);
    indent_level++;
    
    // Generate body
    if (node->children) {
        ASTList* list = node->children;
        while (list) {
            generate_statement(list->node);
            list = list->next;
        }
    }
    
    indent_level--;
    fprintf(output, "}\n\n");
}

void generate_statement(ASTNode* node) {
    if (!node) return;
    
    switch (node->type) {
        case NODE_IF:
            generate_if(node);
            break;
        case NODE_RETURN:
            indent(indent_level);
            fprintf(output, "return");
            if (node->left) {
                fprintf(output, " ");
                generate_expr(node->left);
            }
            fprintf(output, ";\n");
            break;
        case NODE_LET:
            // let inside a block
            indent(indent_level);
            fprintf(output, "// let %s = ", node->name);
            if (node->right) generate_expr(node->right);
            fprintf(output, ";\n");
            break;
        case NODE_UNSAFE:
            generate_unsafe(node);
            break;
        case NODE_IDENTIFIER: {
            // Statement that's just an expression (e.g., function call)
            Symbol* sym = lookup_symbol(node->name);
            if (sym && (sym->sym_type == SYM_FN || sym->sym_type == SYM_EXTERN)) {
                indent(indent_level);
                generate_expr(node);
                fprintf(output, ";\n");
            }
            break;
        }
        default:
            // Try as expression
            if (node->type == NODE_BINOP || node->type == NODE_UNOP ||
                node->type == NODE_FUNCTION_CALL) {
                indent(indent_level);
                generate_expr(node);
                fprintf(output, ";\n");
            }
            break;
    }
}

void generate_if(ASTNode* node) {
    if (!node) return;
    
    indent(indent_level);
    fprintf(output, "if (");
    if (node->left) generate_expr(node->left);
    fprintf(output, ") {\n");
    indent_level++;
    
    // Body
    if (node->children) {
        ASTList* list = node->children;
        while (list) {
            generate_statement(list->node);
            list = list->next;
        }
    }
    
    indent_level--;
    indent(indent_level);
    fprintf(output, "}");
    
    // Else block
    if (node->right) {
        if (node->right->type == NODE_ELSE_IF) {
            fprintf(output, " else ");
            generate_if(node->right);
        } else if (node->right->type == NODE_ELSE) {
            fprintf(output, " else {\n");
            indent_level++;
            if (node->right->children) {
                ASTList* list = node->right->children;
                while (list) {
                    generate_statement(list->node);
                    list = list->next;
                }
            }
            indent_level--;
            indent(indent_level);
            fprintf(output, "}");
        }
    }
    fprintf(output, "\n");
}

void generate_every(ASTNode* node) {
    if (!node) return;
    
    static int every_counter = 0;
    int id = every_counter++;
    const char* name = node->value.string ? node->value.string : "anonymous";
    
    // Get interval in milliseconds
    int interval_ms = 1000;
    if (node->left && node->left->type == NODE_INTEGER) {
        interval_ms = node->left->value.integer;
    }
    
    fprintf(output, "// Every block: %s\n", name);
    fprintf(output, "static unsigned long every_%d_last = 0;\n", id);
    fprintf(output, "void every_%d() {\n", id);
    indent_level++;
    
    fprintf(output, "if (millis() - every_%d_last >= %d) {\n", id, interval_ms);
    indent_level++;
    fprintf(output, "every_%d_last = millis();\n", id);
    
    // Body
    if (node->children) {
        ASTList* list = node->children;
        while (list) {
            generate_statement(list->node);
            list = list->next;
        }
    }
    
    indent_level--;
    fprintf(output, "}\n");
    indent_level--;
    fprintf(output, "}\n\n");
}

// ============================================================
// Function code generation
// ============================================================

void generate_fn(ASTNode* node) {
    if (!node) return;
    
    const char* name = node->name;
    const char* return_type = c_type_name(node->data_type);
    
    fprintf(output, "// Function: %s\n", name);
    fprintf(output, "%s %s(", return_type, name);
    
    // Parameters
    if (node->right && node->right->children) {
        ASTList* params = node->right->children;
        bool first = true;
        while (params) {
            if (params->node->type == NODE_PARAM) {
                if (!first) fprintf(output, ", ");
                fprintf(output, "%s %s", 
                        c_type_name(params->node->data_type),
                        params->node->name);
                first = false;
            }
            params = params->next;
        }
    }
    fprintf(output, ") {\n");
    indent_level++;
    
    // Body
    if (node->children) {
        ASTList* list = node->children;
        while (list) {
            generate_statement(list->node);
            list = list->next;
        }
    }
    
    // Default return if no return statement
    if (node->data_type != TYPE_VOID) {
        indent(indent_level);
        fprintf(output, "return 0;\n");
    }
    
    indent_level--;
    fprintf(output, "}\n\n");
}

// ============================================================
// State machine code generation
// ============================================================

void generate_machine(ASTNode* node) {
    if (!node) return;
    
    const char* name = node->name;
    
    fprintf(output, "// ============================================================\n");
    fprintf(output, "// State Machine: %s\n", name);
    fprintf(output, "// ============================================================\n\n");
    
    // State enum
    fprintf(output, "typedef enum {\n");
    indent_level++;
    
    // Collect states
    if (node->children) {
        ASTList* list = node->children;
        while (list) {
            if (list->node->type == NODE_STATE_DECL || 
                list->node->type == NODE_INITIAL_STATE) {
                indent(indent_level);
                const char* state_name = list->node->name;
                fprintf(output, "STATE_%s_%s", sanitize_name(name), sanitize_name(state_name));
                if (list->node->type == NODE_INITIAL_STATE) {
                    fprintf(output, " = 0");
                }
                fprintf(output, ",\n");
            }
            list = list->next;
        }
    }
    
    indent_level--;
    fprintf(output, "} MachineState_%s;\n\n", sanitize_name(name));
    
    // State variable
    fprintf(output, "static MachineState_%s machine_%s_state = STATE_%s_initial;\n\n",
            sanitize_name(name), sanitize_name(name), sanitize_name(name));
    
    // State transition function
    fprintf(output, "void machine_%s_transition(MachineState_%s new_state) {\n",
            sanitize_name(name), sanitize_name(name));
    indent_level++;
    fprintf(output, "machine_%s_state = new_state;\n", sanitize_name(name));
    indent_level--;
    fprintf(output, "}\n\n");
    
    // Process function
    fprintf(output, "void machine_%s_process() {\n", sanitize_name(name));
    indent_level++;
    fprintf(output, "switch (machine_%s_state) {\n", sanitize_name(name));
    indent_level++;
    
    // Generate state handlers
    if (node->children) {
        ASTList* list = node->children;
        while (list) {
            if (list->node->type == NODE_STATE_DECL || 
                list->node->type == NODE_INITIAL_STATE) {
                const char* state_name = list->node->name;
                fprintf(output, "case STATE_%s_%s:\n", 
                        sanitize_name(name), sanitize_name(state_name));
                indent_level++;
                
                // Generate on_enter if present
                if (list->node->children) {
                    ASTList* inner = list->node->children;
                    while (inner) {
                        if (inner->node->type == NODE_ON_ENTER) {
                            fprintf(output, "// on_enter\n");
                            if (inner->node->children) {
                                ASTList* body = inner->node->children;
                                while (body) {
                                    generate_statement(body->node);
                                    body = body->next;
                                }
                            }
                        }
                        inner = inner->next;
                    }
                }
                
                // Generate transitions
                // (Simplified - would need to evaluate conditions)
                
                indent_level--;
                fprintf(output, "break;\n");
            }
            list = list->next;
        }
    }
    
    indent_level--;
    fprintf(output, "}\n");
    indent_level--;
    fprintf(output, "}\n\n");
}

// ============================================================
// Expression generation
// ============================================================

void generate_expr(ASTNode* node) {
    if (!node) return;
    
    switch (node->type) {
        case NODE_INTEGER:
            fprintf(output, "%d", node->value.integer);
            break;
            
        case NODE_FLOAT:
            fprintf(output, "%f", node->value.float_val);
            break;
            
        case NODE_IDENTIFIER:
            fprintf(output, "%s", node->name);
            break;
            
        case NODE_BINOP:
            fprintf(output, "(");
            generate_expr(node->left);
            fprintf(output, " %s ", node->value.string);
            generate_expr(node->right);
            fprintf(output, ")");
            break;
            
        case NODE_UNOP:
            if (strcmp(node->value.string, "not") == 0) {
                fprintf(output, "!");
                generate_expr(node->left);
            } else {
                fprintf(output, "%s", node->value.string);
                generate_expr(node->left);
            }
            break;
            
        case NODE_FUNCTION_CALL:
            fprintf(output, "%s(", node->name);
            if (node->children) {
                ASTList* args = node->children;
                bool first = true;
                while (args) {
                    if (!first) fprintf(output, ", ");
                    generate_expr(args->node);
                    first = false;
                    args = args->next;
                }
            }
            fprintf(output, ")");
            break;
            
        case NODE_QUESTION:
            // ? operator - read sensor with Option<T> semantics
            fprintf(output, "sensor_%s_read_opt()", sanitize_name(node->name));
            break;
            
        case NODE_IS:
            // is operator
            generate_expr(node->left);
            fprintf(output, " == ");
            fprintf(output, "%s", strcmp(node->value.string, "ON") == 0 ? "true" : "false");
            break;
            
        case NODE_STATE_LITERAL:
            fprintf(output, "%s", strcmp(node->value.string, "ON") == 0 ? "true" : "false");
            break;
            
        default:
            fprintf(output, "/* unknown expression */");
            break;
    }
}

// ============================================================
// Other code generation
// ============================================================

void generate_invariant(ASTNode* node) {
    if (!node) return;
    
    const char* name = node->value.string ? node->value.string : "anonymous";
    
    fprintf(output, "// Invariant: %s\n", name);
    fprintf(output, "static bool invariant_%s() {\n", sanitize_name(name));
    indent_level++;
    fprintf(output, "return (");
    if (node->left) generate_expr(node->left);
    fprintf(output, ");\n");
    indent_level--;
    fprintf(output, "}\n\n");
}

void generate_emit(ASTNode* node) {
    if (!node) return;
    
    const char* payload = node->name;
    const char* protocol = node->value.string ? node->value.string : "MQTT";
    const char* address = node->left ? node->left->name : "default";
    
    fprintf(output, "// Emit: %s to %s(%s)\n", payload, protocol, address);
    fprintf(output, "static void emit_%s(", sanitize_name(payload));
    // Generate function signature based on payload fields
    Symbol* sym = lookup_symbol(payload);
    if (sym && sym->fields) {
        Symbol* field = sym->fields;
        bool first = true;
        while (field) {
            if (!first) fprintf(output, ", ");
            fprintf(output, "%s %s", c_type_name(field->data_type), field->name);
            first = false;
            field = field->next;
        }
    }
    fprintf(output, ") {\n");
    indent_level++;
    
    // Generate serialization
    fprintf(output, "// TODO: Implement %s serialization to %s\n", payload, protocol);
    
    indent_level--;
    fprintf(output, "}\n\n");
}

void generate_init(ASTNode* node) {
    if (!node) return;
    
    fprintf(output, "// Initialization\n");
    fprintf(output, "static void init_crop() {\n");
    indent_level++;
    
    // Body
    if (node->children) {
        ASTList* list = node->children;
        while (list) {
            // Assume these are C statements
            if (list->node->type == NODE_UNSAFE) {
                generate_unsafe(list->node);
            } else {
                indent(indent_level);
                fprintf(output, "// %s (C code not supported in init block)\n", 
                        node_type_name(list->node->type));
            }
            list = list->next;
        }
    }
    
    indent_level--;
    fprintf(output, "}\n\n");
}

void generate_unsafe(ASTNode* node) {
    if (!node) return;
    
    indent(indent_level);
    if (node->value.string) {
        fprintf(output, "// Unsafe C code:\n");
        indent(indent_level);
        fprintf(output, "%s\n", node->value.string);
    } else {
        fprintf(output, "/* unsafe block */\n");
    }
}

void generate_extern(ASTNode* node) {
    if (!node) return;
    
    const char* name = node->name;
    const char* return_type = c_type_name(node->data_type);
    const char* lang = node->value.string ? node->value.string : "C";
    
    fprintf(output, "// External function: %s (%s)\n", name, lang);
    fprintf(output, "extern %s %s(", return_type, name);
    
    if (node->children) {
        ASTList* params = node->children;
        bool first = true;
        while (params) {
            if (params->node->type == NODE_PARAM) {
                if (!first) fprintf(output, ", ");
                fprintf(output, "%s %s", 
                        c_type_name(params->node->data_type),
                        params->node->name);
                first = false;
            }
            params = params->next;
        }
    }
    fprintf(output, ");\n\n");
}

// ============================================================
// Main loop generation
// ============================================================

void generate_main_loop() {
    fprintf(output, "// ============================================================\n");
    fprintf(output, "// Main loop\n");
    fprintf(output, "// ============================================================\n\n");
    
    fprintf(output, "void setup() {\n");
    indent_level++;
    fprintf(output, "init_crop();\n");
    indent_level--;
    fprintf(output, "}\n\n");
    
    fprintf(output, "void loop() {\n");
    indent_level++;
    
    fprintf(output, "// Update sensors\n");
    // We need to collect all sensor names from the symbol table
    fprintf(output, "// (Sensors are updated on-demand via ? operator)\n\n");
    
    fprintf(output, "// Run rules\n");
    // We need to collect all rule names
    fprintf(output, "// (Rules are generated as rule_* functions)\n\n");
    
    fprintf(output, "// Process state machines\n");
    // We need to collect all machine names
    fprintf(output, "// (Machines are generated as machine_*_process functions)\n\n");
    
    // For the test hello.crop example:
    fprintf(output, "// Generated rules and every blocks will be called here\n");
    fprintf(output, "// (This is auto-generated by the compiler)\n\n");
    
    indent_level--;
    fprintf(output, "}\n");
}

// ============================================================
// Backward compatibility for old code
// ============================================================

bool check_invariants(ASTNode* node) {
    // Simplified invariant checking
    // In a real implementation, this would call Z3
    printf("  ✓ Invariants check passed (SMT verification not yet integrated)\n");
    return true;
}
